# Generated by Django 5.1.3 on 2024-12-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admn_num',
            new_name='phone',
        ),
    ]
