# Generated by Django 5.1.3 on 2024-12-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default=0, upload_to='gallery/'),
        ),
    ]
