# Generated by Django 5.1.3 on 2024-12-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fl',
            field=models.FileField(default=0, upload_to='documents/'),
        ),
    ]
